// <auto-generated />
using MASZ.GuildAudits.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MASZ.GuildAudits.Migrations
{
    [DbContext(typeof(GuildAuditDatabase))]
    partial class GuildAuditDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("GuildAudits")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MASZ.GuildAudits.Models.GuildAuditConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("GuildAuditEvent")
                        .HasColumnType("int");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("PingRoles")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GuildAuditConfigs", "GuildAudits");
                });
#pragma warning restore 612, 618
        }
    }
}
