// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoleReactions.Data;

#nullable disable

namespace RoleReactions.Migrations
{
    [DbContext(typeof(RoleReactionsDatabase))]
    partial class RoleReactionsDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("RoleReactions")
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RoleReactions.Models.RoleMenu", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("MenuName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Emotes")
                        .HasColumnType("longtext");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Roles")
                        .HasColumnType("longtext");

                    b.HasKey("GuildId", "ChannelId", "MenuName");

                    b.ToTable("RoleReactionsMenu", "RoleReactions");
                });

            modelBuilder.Entity("RoleReactions.Models.UserRoles", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("RoleIds")
                        .HasColumnType("longtext");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("UserRoles", "RoleReactions");
                });
#pragma warning restore 612, 618
        }
    }
}
