// <auto-generated />
using System;
using MASZ.Invites.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MASZ.Invites.Migrations
{
    [DbContext(typeof(InviteDatabase))]
    partial class InviteDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Invites")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MASZ.Invites.Models.UserInvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime?>("InviteCreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("InviteIssuerId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("JoinedUserId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("TargetChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("UsedInvite")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserInvites", "Invites");
                });
#pragma warning restore 612, 618
        }
    }
}
