// <auto-generated />
using System;
using Greeting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Greeting.Migrations
{
    [DbContext(typeof(GreeterDatabase))]
    [Migration("20231104134048_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Greeting")
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Greeting.Models.GreetGateModel", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("AllowedGreetChannels")
                        .HasColumnType("longtext");

                    b.Property<string>("AllowedGreetRoles")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("DisallowedMuteExistence")
                        .HasColumnType("time(6)");

                    b.Property<string>("DisallowedMuteRoles")
                        .HasColumnType("longtext");

                    b.Property<ulong>("LoggingChannel")
                        .HasColumnType("bigint unsigned");

                    b.Property<TimeSpan>("PunishmentTime")
                        .HasColumnType("time(6)");

                    b.HasKey("GuildId");

                    b.ToTable("GreeterConfigs", "Greeting");
                });
#pragma warning restore 612, 618
        }
    }
}
