// <auto-generated />
using GuildAudits.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuildAudits.Migrations
{
    [DbContext(typeof(GuildAuditDatabase))]
    [Migration("20220829141452_GuildAuditIgnoreChannels")]
    partial class GuildAuditIgnoreChannels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("GuildAudits")
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GuildAudits.Models.GuildAuditConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("GuildAuditLogEvent")
                        .HasColumnType("int");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("IgnoreChannels")
                        .HasColumnType("longtext");

                    b.Property<string>("IgnoreRoles")
                        .HasColumnType("longtext");

                    b.Property<string>("PingRoles")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GuildAuditConfigs", "GuildAudits");
                });
#pragma warning restore 612, 618
        }
    }
}
